document:
  name: Linee guida per l'erogazione del servizio pubblico wi-fi free
  description: |
    Linee guida per l'erogazione del servizio pubblico wi-fi free
  tags:
    - wi-fi
    - free wi-fi
